### ISSUE TITLE
PROXIES

### ISSUE THREAD

**Issue by Cyberfilo** [BrailyGuzman/NGL.LINK-Spammer#2]
hey  everyone, I worked a bit on this code and published a proxy version to send more requests and not get your IP blocked by NGL

https://github.com/Cyberfilo/NGL.link-spammer-with-proxies

**Comment by BrailyGuzman** [comment]
BRO WHAT THE HELL ARE YOU DOING??... FIND GOD

**Comment by BrailyGuzman** [comment]
# Dude, you stole my code and made it even worse.
# You even changed who it was made by. You could've contributed to my repository but you decided to skid rip it.

![image](https://user-images.githubusercontent.com/94770717/196065745-123b86b2-669e-4e6a-b8ec-e2be4c9ab9df.png)
